# Site settings
title: Medeski Design
email: josh@medeskidesign.com
description: Custom WordPress, front-end development and graphic design for entrepreneurs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://medeskidesign.com" # the base hostname & protocol for your site
twitter_username: joshmedeski
github_username:  joshmedeski

# Build settings
markdown: kramdown

# Outputting
permalink: /:year/:month/:day/:title.html
